In [1]:
import pandas as pd
import numpy as np
import requests, time
from bs4 import BeautifulSoup
import sqlalchemy

pd.set_option('display.max_columns', None)

In [2]:
name_table = 'kick_punt_returns'

In [3]:
url = 'http://pfref.com/pi/share/21dgO'

In [4]:
def read_html(url):
    pd.read_html(url)
   
    return pd.read_html(url)


def convert_df(lista):
    lista[0]
    
    return lista[0]


def rm_unnamed_col(dado):
    dt = dado.rename(columns={'Unnamed: 0_level_0':'',
                        'Unnamed: 1_level_0': '', 
                        'Unnamed: 2_level_0': '',
                        'Unnamed: 3_level_0': '',
                        'Unnamed: 4_level_0': '' ,
                        'Unnamed: 17_level_0': ''})
    return dt

def add_col_characters(dataframe):
    dataframe.loc[:,'All-Pro'] = dataframe['','Player'].str.contains('+', regex=False)
    dataframe.loc[:,'Selected_Pro_Bowl'] = dataframe['','Player'].str.contains('*', regex=False)
   
    return dataframe

def clean_col_player(uva):
    uva['','Player'] = uva['', 'Player'].str.replace('*','')
    uva['','Player'] = uva['', 'Player'].str.replace('+','')
    
    return uva

def limpar_todas_coluna(manga):
    manga.columns = [(c.lower().strip() + ' '+ d.lower().strip()).strip() for c,d in manga.columns]
    
    return manga.columns

In [5]:
def robo(url):
    lista = read_html(url)
    converter_em_dataframe = convert_df(lista)
    tirar_nomes_coluna= rm_unnamed_col(converter_em_dataframe)
    adicionar_colunas_novas = add_col_characters(tirar_nomes_coluna)
    limpar_coluna_player = clean_col_player(adicionar_colunas_novas)
    dataframe_final = limpar_todas_coluna(limpar_coluna_player)
    
    return tirar_nomes_coluna

In [6]:
robo(url)

C:\Users\mateu\AppData\Local\Temp\ipykernel_19376\2428384703.py:29: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  uva['','Player'] = uva['', 'Player'].str.replace('*','')
C:\Users\mateu\AppData\Local\Temp\ipykernel_19376\2428384703.py:30: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  uva['','Player'] = uva['', 'Player'].str.replace('+','')

,rk,player,tm,age,pos,games g,games gs,punt returns ret,punt returns yds,punt returns td,punt returns lng,punt returns y/r,kick returns rt,kick returns yds,kick returns td,kick returns lng,kick returns y/rt,apyd,all-pro,selected_pro_bowl
0,1,Dax Milne,WAS,23,WR,15,1,40.0,311.0,0,19.0,7.8,15.0,300.0,0,33.0,20.0,648,False,False
1,2,Ray-Ray McCloud,SFO,26,WR,17,2,33.0,356.0,0,35.0,10.8,26.0,599.0,0,39.0,23.0,1276,False,False
2,3,Britain Covey,PHI,25,WR,17,0,33.0,308.0,0,27.0,9.3,10.0,206.0,0,26.0,20.6,514,False,False
3,4,Jaelon Darden,2TM,23,NaN,14,0,33.0,345.0,0,24.0,10.5,3.0,67.0,0,25.0,22.3,440,False,False
4,5,Trent Taylor,CIN,28,WR,16,1,33.0,340.0,0,27.0,10.3,2.0,15.0,0,9.0,7.5,432,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,160,Jalen Virgil,DEN,24,WR,9,1,NaN,NaN,0,NaN,NaN,1.0,21.0,0,21.0,21.0,96,False,False
160,161,Jonathan Ward,2TM,25,NaN,8,0,NaN,NaN,0,NaN,NaN,1.0,25.0,0,25.0,25.0,57,False,False
161,162,Jonathan Williams,WAS,28,RB,13,2,NaN,NaN,0,NaN,NaN,1.0,19.0,0,19.0,19.0,211,False,False
162,163,Russ Yeast,LAR,23,S,15,1,NaN,NaN,0,NaN,NaN,1.0,29.0,0,29.0,29.0,29,False,False
163,164,Brandon Zylstra,DET,29,WR,2,0,NaN,NaN,0,NaN,NaN,1.0,19.0,0,19.0,19.0,19,False,False

In [7]:
db_server='pymysql'
user='root'
db_port = '3306'
password = ''
ip = 'localhost'
db_name = 'nflcopy'
engine = sqlalchemy.create_engine(f'mysql+{db_server}://{user}:{password}@{ip}:{db_port}/{db_name}?charset=utf8')
robo(url).to_sql(name_table, engine, index=False, if_exists='replace')

C:\Users\mateu\AppData\Local\Temp\ipykernel_19376\2428384703.py:29: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  uva['','Player'] = uva['', 'Player'].str.replace('*','')
C:\Users\mateu\AppData\Local\Temp\ipykernel_19376\2428384703.py:30: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  uva['','Player'] = uva['', 'Player'].str.replace('+','')

164